### ISSUE TITLE
crash and cann't open xcode Version 5.1.1 (5B1008)

### ISSUE THREAD

**Issue by sunjun** [qfish/XAlign#45]
crash cann't open on xcode Version 5.1.1 (5B1008)
anyone same as me?
how to fix it??

**Comment by sunjun** [comment]
after update to mac os x 10.10.1, it works now

**Comment by cerniuk** [comment]
I dropped Alcatraz as it seemed to be more trouble than it was worth and instead learned to write plugins so I could install the silly things.

One element to note is that the plugin must have the special secret code to activate under a given release of Xcode. Why they can't make this more straight forward is anyone's guess. The messyness is located in the "Info" section to the right of "Build Settings" The array named "DVTPlugInCompatiblityUUIDs" must contain the UUID of the latest Xcode app to have the Xcode app load the plugin.  In the case of Xcode 6.2b3, that value is FEC992CC-CA4A-4CFD-8881-77300FCB848A .   You can add it manually to the project before you build it... hence the reason I stopped using Alcatraz.

Apple: Using the UUID is an over-complication. (hard to find, cannot guess, etc) A simple version string check for an array named "CompatibleWithXcodeVersions" and then "6.2.0" would make so much more sense visually and be easier to find than. (sigh)

Thanks for your efforts on XAlign! I learned quite a bit by having to stumble around this badly documented Apple convention for supporting plugins. Respect!
