### ISSUE TITLE
Installing in Xcode 6.2b3 ... Tango Uniform... Breaks Alcatraz Too

### ISSUE THREAD

**Issue by cerniuk** [qfish/XAlign#46]
Using Alcatraz to install produced empty Package (repeated tries, same result):

![xalign_xcplugin](https://cloud.githubusercontent.com/assets/369530/5548524/57a0b5ae-8b41-11e4-8433-315c22669304.png)

Installing using 
    curl http://qfi.sh/XAlign/build/install.sh | sh 
installs full plugin but the plug in fails to activate and neither can be invoked via command key nor appears in menu. Installation, for some reason, requires admin privileges?

Removing XAlign.xcplugin from the Xcode plug ins folder by deleting in the Finder requires admin privileges (?) and afterwards, Alcatraz will fail to perform an install of the same plugin.

Putting XAlign.xcplugin back into the Xcode plug ins folder requires admin privileges (something amiss with the XAlign.xcplugin package guts..).

Uninstalling XAlign.xcplugin using the uninstall command provided by the developer:
    curl http://qfi.sh/XAlign/build/uninstall.sh | sh
uninstalls the plug in.

After uninstalling XAlign.xcplugin, Alcatraz is broken. Alcatraz's controls all work except the install / uninstall buttons. Quitting and re-running Xcode does not fix Alcatraz. 

Removing Alcatraz's cached data using:
    rm -rf ~/Library/Application\ Support/Alcatraz
does not restore Alcatraz to an operational state.

Removing Alcatraz in the Finder (or using the 'rm' command, same thing), then reinstalling using:
    curl -fsSL https://raw.github.com/supermarin/Alcatraz/master/Scripts/install.sh | sh
does not bring Alcatraz back to operation.  Alcatraz's window will open but no install "buttons" work.  All other controls still work in the Alcatraz window short of the install buttons to the left of each plugin (etc) listed.

Starting to have serious concerns about the install of XAlign including and especially the need for admin privileges to install it... How (why?) did it manage to only break Alcatraz's ability to install / uninstall.

**Comment by nicolasgoutaland** [comment]
Hi there, any hint for a fix ?
Last Xcode release seems to broke all XCode plug-ins.
Nor Alcatraz, XAlign, etc... seems to be loaded at launch.

**Comment by nicolasgoutaland** [comment]
Hi, seems to be a problem with DVTPlugInCompatibilityUUIDs key in plist.

See here for a fix
https://github.com/supermarin/Alcatraz/issues/218

Regards

**Comment by qfish** [comment]
Hi @nicolasgoutaland, thanks! Fixed.
