### ISSUE TITLE
如何对“<-”这个符号对齐？那个plist文件不会改...

### ISSUE THREAD

**Issue by DragonManYo** [qfish/XAlign#63]
复制了个节点，改了specifer参数，但没有作用呢。希望能得到帮忙呢～谢谢啦

**Comment by qfish** [comment]
`specifer` 用来识别对齐的模式，你需要改`patterns`，`patterns` 是正则，把要对齐的部分划分开。

![banners_and_alerts_and_patterns_plist](https://cloud.githubusercontent.com/assets/679824/8512340/7ea817ec-2370-11e5-89ec-8e9418c727be.jpg)

你可以参考 `=` 的写法，如果新增的 `specifer` 是 `<-`，要对其的代码里如果有 `<-`，就会通过你写的`patterns` 来处理。

**Comment by DragonManYo** [comment]
感谢 我研究下～
