### ISSUE TITLE
Not working in xcode 7 

### ISSUE THREAD

**Issue by Premal-Khetani** [qfish/XAlign#68]
I tried to install it all the ways but not yet working with xcode 7 

While doing command line installation i am getting following error.  

-bash: read: `/Applications/Xcode.app/Contents/Info': not a valid identifier

Kindly solve it . :)

**Comment by qfish** [comment]
Have you tried this ?
```sh
curl -fsSL http://qfi.sh/XAlign/build/install.sh | sh
```

**Comment by Premal-Khetani** [comment]
It installed successfully but not working in xcode :(

**Comment by qfish** [comment]
Is there an `XAlign.xcplugin` under this path `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/`?

**Comment by Premal-Khetani** [comment]
Yes there is a file named XAlign.xcplugin

**Comment by yaosj** [comment]
It works in Xcode6. But  did not work in Xcode7.

**Comment by Premal-Khetani** [comment]
Oky would it be solve?

Best Regards,
Premal Khetani
iOS Application Developer
8140949071

**Comment by qfish** [comment]
Have you got the `Load Bundles` alert on starting Xcode ?

**Comment by Premal-Khetani** [comment]
No, i am not getting Alert.

**Comment by qfish** [comment]
My version is 7.0 (7A220), what's yours ?

**Comment by Premal-Khetani** [comment]
its xcode 7.0.1(7A1001)

**Comment by qfish** [comment]
Thank you, I'll get an Xcode 7.0.+ and take care of this issue as soon as possible. :)

**Comment by Premal-Khetani** [comment]
Thanks

**Comment by KaiJSchaefer** [comment]
I solved my problem with this =>  "defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1"

**Comment by Premal-Khetani** [comment]
@KaiJSchaefer  What you did? i didn't Get your answer.

**Comment by qfish** [comment]
Open the terminal:
```sh
defaults delete com.apple.dt.Xcode DVTPlugInManagerNonApplePlugIns-Xcode-7.1
```

**Comment by Premal-Khetani** [comment]
@qfish I did this but it showing some error as below :
Domain (com.apple.dt.Xcode) not found.
Defaults have not been changed.

**Comment by ferologics** [comment]
@qfish the command fixed my problem as well :+1:

**Comment by Premal-Khetani** [comment]
It's solved by reinstalling the plugin @qfish  Thanks :+1:
