### ISSUE TITLE
xcode8不可用

### ISSUE THREAD

**Issue by AMEstudio** [qfish/XAlign#90]
我用了这个,解锁了我的xcode8
https://github.com/fpg1503/MakeXcodeGr8Again 
然后升级了uuid给插件
插件不可用,按快捷键时候代码消失,并生成了一个怪异的字符

**Comment by liangpengfei** [comment]
希望能尽快支持Xcode8

**Comment by qfish** [comment]
Xcode 8 is supported! Check https://github.com/qfish/XAlign#install-on-xcode-8
