### ISSUE TITLE
Not working with XCode 8

### ISSUE THREAD

**Issue by BlaineOmega** [qfish/XAlign#91]
I have tried installing XAlign all three ways, and tried the troubleshooting, but it doesn't appear to be working with xcode 8. The plugin isn't showing under the editor table and it doesn't work with the shortcut.

**Comment by reza-khalafi** [comment]
Try this: 

XCODEUUID=`defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`
for f in ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins/*; do defaults write "$f/Contents/Info" DVTPlugInCompatibilityUUIDs -array-add $XCODEUUID; done

**Comment by srikanth-vm** [comment]
@BlaineOmega From Xcode 8 they have stopped supporting plugins in a straight forward way. You can still get it working by modifying UUID. But was hoping to find a Xcode extension. We need to convert plugin to extension.

Lets make xAlign great again !

**Comment by qfish** [comment]
Coming soon! https://github.com/qfish/XAlign/issues/92

**Comment by qfish** [comment]
Xcode 8 is supported! Check https://github.com/qfish/XAlign#install-on-xcode-8
