### ISSUE TITLE
There is no XAlign.app in XAlign.dmg

### ISSUE THREAD

**Issue by huangwei4478** [qfish/XAlign#95]
Hi, qfish:

I just downloaded the dmg from the link in readme.md, double clicked but there is **no** XAlign.app for me to drag into the Application folder.

Screencast png is provided below: 
[XAlign.dmg_missing_XAlign.app_problem.png](http://p1.bpimg.com/4851/9e71f6d0a090af34.png)

Environment: 
- maxOS 10.12.1
- Xcode 8.1

hw

**Comment by qfish** [comment]
qq: 56219285,  please contact me, thank you!

**Comment by qfish** [comment]
Thank you, fixed ! https://github.com/qfish/XAlign/issues/92#issuecomment-260357918
