### ISSUE TITLE
Xcode 8.1 still not working

### ISSUE THREAD

**Issue by arthankamal** [qfish/XAlign#98]
After installing XAlign into Applications, and opened the XAlign.app.
But in "Preferences -> Extensions", not able to see "Xcode Source Editor"

**Comment by qfish** [comment]
What's your macOS version ?

**Comment by arthankamal** [comment]
OS X El Capitan 10.11.6

**Comment by arthankamal** [comment]
I installed Mac OS Sierra (10.12). and i'm able to find the **XAlign** in " *Preferences -> Extensions -> All Third Party Extensions"*. I checked the **XAlign** there and now i'm able to see it in **Xcode Source Editor** section
